# Generated by Django 4.0.2 on 2022-03-09 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passwords', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordentry',
            name='vault',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_entry', to='passwords.passwordvault'),
        ),
    ]
